name: "Secrets Sync"

description: "Sync secrets across multiple repositories"

author: "xt0rted"

branding:
  icon: "refresh-cw"
  color: "purple"

inputs:
  config:
    description: "Path of the config file to use"
    required: false
    default: "secrets-sync.yml"

  repo_token:
    description: "Repo scoped Personal Access Token or GitHub App Token"
    required: true

  filter_repos:
    description: "Comma separated list of repos that should be processed. Any not in the list will be skipped."
    required: false

  filter_secrets:
    description: "Comma separated list of secrets that should be processed. Any not in the list will be skipped."
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
