name: CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 17]

    steps:
      - name: Check out repo
        uses: actions/checkout@v3.0.0

      - name: Install Node
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm run lint

      - run: npm run build

      - run: npm test

      - run: npm run package
        if: ${{ matrix.node != 17 }}

      - run: npm run package:17
        if: ${{ matrix.node == 17 }}
